name: ci

on:
  push:
    branches:
      - 'feature/ci'
      - '!feature/connect-ci'
jobs:
  connect-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create report file
        run: |
          date +%s > report.txt
          git status --porcelain
          git config --global commit.gpgsign false
          git config --global user.name '4 CI Robot'
          git config --global user.email '111610370+4-ci-robot@users.noreply.github.com'
          gpg --list-secret-keys --keyid-format=long
          export GPG_TTY=$(tty)
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY_ROBOT }}
          fingerprint: ${{ secrets.SIGN_KEY_ROBOT }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: list public keys after
        run: |
          gpg --list-keys
          gpg --list-secret-keys --keyid-format=long
      - name: check git config
        run: |
          git config --global --list
      - name: change git branch
        run: |
          git checkout -b feature/connect-${{ github.sha }}
      - name: List keys
        run: |
          gpg -K  
          gpg -s --default-key ${{ secrets.SIGN_KEY_ROBOT }}
      - name: Commit changes
        id: commit
        run: |
          git status --porcelain
          git add .
          git commit -S -m "This commit is signed!"
          git log
#          curl whatthecommit.com/index.txt | git commit -S -F -
#          git push ${{ secrets.TOKEN_4_CI_ROBOT_ACTION }}