name: ci

on:
  push:
    branches:
      - 'feature/ci'
      - '!feature/connect-ci'
jobs:
  connect-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create report file
        run: |
          date +%s > report.txt
          git status --porcelain
          git config --global commit.gpgsign false
          git config --global user.name '4 CI Robot'
          git config --global user.email '111610370+4-ci-robot@users.noreply.github.com'
      - name: check git config I
        run: |
          git config --global --list
      - name: list public keys before
        run: |
          gpg --list-keys
          gpg --list-secret-keys --keyid-format=long
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY_ROBOT }}
#          passphrase:
#      - name: import public keys
#        env:
#          GPG_KEY_PUB_ROBOT: ${{ secrets.GPG_KEY_PUB_ROBOT }}
#        run: |
#          echo -n "$GPG_KEY_PUB_ROBOT" | base64 --decode | gpg --import
#          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
#          echo $GPG_KEY_PUB_ROBOT > ciKey.key
#          cat ciKey.key
#          gpg --import ciKey.key
#          rm -Rf ciKey.key
#          git status --porcelain
      - name: list public keys after
        run: |
          gpg --list-keys
          gpg --list-secret-keys --keyid-format=long
      - name: set user signingKey
        run: |
          git config commit.gpgsign true
          git config --global user.signingKey ${{ secrets.SIGN_KEY_ROBOT }}
      - name: check git config II
        run: |
          git config --global --list
      - name: change git branch
        run: |
          git checkout -b feature/connect-${{ github.sha }}
#      - name: import keys
#        id: keys
#        run: |
#          export GPG_TTY=$(tty)
#          gpg --passwd 111610370+4-ci-robot@users.noreply.github.com
#          git commit -S -m "report file!!"
      - name: Commit changes
        id: commit
        run: |
          git status --porcelain
          git fetch
          git add -A
          curl whatthecommit.com/index.txt | git commit -S -F -
          git log
          git push ${{ secrets.TOKEN_4_CI_ROBOT_ACTION }}
#      - name: sign changes
#        id: sign
#        run: |
#          git add -A
#          gpg --passwd 111610370+4-ci-robot@users.noreply.github.com
#          git commit -S -m "report file!!"
#          git log
