name: Release Project

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Extract tag name
        id: extract_tagname
        shell: bash
        # Extra the tagname form the git reference, value of GITHUB_REF will be something like refs/tags/<tag_name>.
        run: echo "##[set-output name=tagname;]$(echo ${GITHUB_REF##*/})"
      - name: Set version with Maven
        run: mvn -B versions:set -DprocessAllModules=true -DnewVersion=${{ steps.extract_tagname.outputs.tagname }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package
        id: publish_package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - uses: actions/checkout@master
#      - name: Microsoft Teams Notification
#        uses: skitionek/notify-microsoft-teams@master
#        if: success()
#        with:
#          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
#          raw: >-
#            {
#              "@type":"MessageCard",
#              "@context":"https://schema.org/extensions",
#              "summary":"Pipeline success!",
#              "themeColor":"3BD16F",
#              "title":"${{ github.event.release.tag_name }} is published!",
#              "sections":[
#                {
#                  "facts":[
#                    {
#                      "name":"Repository:",
#                      "value":"${{ github.repository }}"
#                    },
#                    {
#                      "name":"Author:",
#                      "value":"${{ github.actor }}"
#                    },
#                    {
#                      "name":"Release Name:",
#                      "value":"${{ github.event.release.name }}"
#                    },
#                    {
#                      "name":"Release Description :",
#                      "value":"${{ github.event.release.body }}"
#                    }
#                  ]
#                }
#              ],
#              "markdown": true,
#              "potentialAction":[
#                {
#                  "@type":"OpenUri",
#                  "name":"View Release on GitHub",
#                  "targets":[
#                    {
#                      "os":"default",
#                      "uri":"${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}"
#                    }
#                  ]
#                }
#              ]
#            }